# Generated by Django 4.0.4 on 2022-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msa', models.PositiveIntegerField(blank=True, null=True)),
                ('name_msa', models.CharField(blank=True, max_length=255, null=True)),
                ('fipstate', models.CharField(blank=True, max_length=255, null=True)),
                ('name_country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
